# Generated by Django 5.0.2 on 2025-01-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cashflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('category', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('value_type', models.CharField(choices=[('EXPENSE', 'Gasto'), ('PROFIT', 'Lucro')], max_length=8)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
