# Generated by Django 5.0.2 on 2025-01-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0002_cashflow_created_at_cashflow_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
