# Generated by Django 5.0.2 on 2024-02-26 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11, 'Digite igual o padrão (**) *****-****')])),
                ('bought', models.FloatField(default=0.0)),
            ],
        ),
    ]
