# Generated by Django 5.0.2 on 2024-02-26 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Digite no padrão (**) *****-****', regex='^\\(\\d(2)\\)\\s\\d(5)\\-d(4)$')]),
        ),
    ]
