# Generated by Django 5.0.2 on 2025-01-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='debt',
            field=models.FloatField(default=0.0),
        ),
    ]
