# Generated by Django 5.0.2 on 2024-03-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sale_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='data_hour',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
