# Generated by Django 5.0.2 on 2024-05-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_sale_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='data_hour',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
