# Generated by Django 5.0.2 on 2024-05-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sale_total_alter_sale_data_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='product_description',
            field=models.CharField(default='', max_length=50),
        ),
    ]
