<<<<<<< HEAD
# Generated by Django 5.0.2 on 2024-06-25 01:28
=======
# Generated by Django 5.0.2 on 2024-08-08 02:09
>>>>>>> a944e2c00c87c40bdc405560820e2672fd6dff3e

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("sales", "0009_alter_sale_payment_status_alter_sale_product"),
=======
        ('sales', '0009_alter_sale_payment_status_alter_sale_product'),
>>>>>>> a944e2c00c87c40bdc405560820e2672fd6dff3e
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name="sale",
            name="product",
            field=models.CharField(
                choices=[
                    ("TORTA", "Torta"),
                    ("BRASINHA_COMUM", "Brasinha comum"),
                    ("BRASINHA_GOURMET", "Brasinha gourmet"),
                    ("BOLO_DE_POTE_P", "Bolo de pote P"),
                    ("BOLO_DE_POTE_G", "Bolo de pote G"),
                    ("BOLO_VULCAO_P", "Bolo vulcão P"),
                    ("BOLO_VULCAO_M", "Bolo vulcão M"),
                    ("BOLO_VULCAO_G", "Bolo vulcão G"),
                    ("BOLO_DE_ANIVERSARIO", "Bolo de aniversário"),
                ],
                max_length=30,
            ),
=======
            model_name='sale',
            name='product',
            field=models.CharField(choices=[('TORTA', 'Torta'), ('BROWNIE', 'Brownie'), ('BRASINHA_COMUM', 'Brasinha comum'), ('BRASINHA_GOURMET', 'Brasinha gourmet'), ('BOLO_DE_POTE_P', 'Bolo de pote P'), ('BOLO_DE_POTE_G', 'Bolo de pote G'), ('BOLO_VULCAO_P', 'Bolo vulcão P'), ('BOLO_VULCAO_M', 'Bolo vulcão M'), ('BOLO_VULCAO_G', 'Bolo vulcão G'), ('BOLO_DE_ANIVERSARIO', 'Bolo de aniversário')], max_length=30),
>>>>>>> a944e2c00c87c40bdc405560820e2672fd6dff3e
        ),
    ]
