# Generated by Django 5.0.2 on 2025-01-05 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_sale_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.CharField(choices=[('TORTA', 'Torta'), ('BROWNIE', 'Brownie'), ('BRASINHA_COMUM', 'Brasinha comum'), ('BRASINHA_GOURMET', 'Brasinha gourmet'), ('BOLO_DE_POTE_P', 'Bolo de pote P'), ('BOLO_DE_POTE_G', 'Bolo de pote G'), ('BOLO_VULCAO_P', 'Bolo vulcão P'), ('BOLO_VULCAO_M', 'Bolo vulcão M'), ('BOLO_VULCAO_G', 'Bolo vulcão G'), ('BOLO_VULCAO_GG', 'Bolo vulcão GG'), ('COPO_DA_FELICIDADE', 'Copo da felicidade'), ('BOLO_DE_ANIVERSARIO', 'Bolo de aniversário'), ('FATIA_COM_DOCE', 'Fatia com doce'), ('FATIA_SEM_DOCE', 'Fatia sem doce'), ('PANETONE_TRUFADO', 'Panetone trufado')], max_length=30),
        ),
    ]
