# Generated by Django 5.0.2 on 2026-02-27 19:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_alter_sale_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='data_hour',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.CharField(choices=[('BARRA_DE_CHOCOLATE', 'Barra de chocolate'), ('BOLO_DE_ANIVERSARIO', 'Bolo de aniversário'), ('BOLO_DE_POTE_P', 'Bolo de pote P'), ('BOLO_DE_POTE_G', 'Bolo de pote G'), ('BOLO_VULCAO_P', 'Bolo vulcão P'), ('BOLO_VULCAO_M', 'Bolo vulcão M'), ('BOLO_VULCAO_G', 'Bolo vulcão G'), ('BOLO_VULCAO_GG', 'Bolo vulcão GG'), ('BRASINHA_COMUM', 'Brasinha comum'), ('BRASINHA_GOURMET', 'Brasinha gourmet'), ('BRIGADEIRO', 'Brigadeiro'), ('BROWNIE', 'Brownie'), ('COPO_DA_FELICIDADE', 'Copo da felicidade'), ('FATIA_COM_DOCE', 'Fatia com doce'), ('FATIA_SEM_DOCE', 'Fatia sem doce'), ('MINI_COPO_DA_FELICIDADE', 'Mini copo da felicidade'), ('OVO_DE_PASCOA', 'Ovo de pascoa'), ('PANETONE_TRUFADO', 'Panetone trufado'), ('TORTA', 'Torta'), ('TORTA_DE_PAO', 'Torta de pão'), ('TORTA_NO_POTE', 'Torta no pote'), ('TRUFA', 'Trufa')], max_length=30),
        ),
    ]
